.TH "C:/arbitros/trunk/rtos/source/common/arb_console.c" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/rtos/source/common/arb_console.c \- 
.PP
Main handler for the system console interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'arb_error\&.h'\fP
.br
\fC#include 'arb_thread\&.h'\fP
.br
\fC#include 'arb_device\&.h'\fP
.br
\fC#include 'arb_sysTimer\&.h'\fP
.br
\fC#include 'arb_console\&.h'\fP
.br
\fC#include 'arb_printf\&.h'\fP
.br
\fC#include 'arb_scheduler\&.h'\fP
.br
\fC#include 'drv_console\&.h'\fP
.br
\fC#include 'drv_sd\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBt_consoleObject\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRINTF_NUM_LINES_TO_PRINT\fP   (20)"
.br
.RI "\fIThis macro controls the number of lines displayed to the terminal when printing the contents of a file using the command 'head'\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "t_error \fBarb_consoleInit\fP (char *pc_driver, t_stackSize t_stack, t_thrdPrio t_pri, bool(*pf_funPtr)(t_DEVHANDLE t_consoleHndl, int8_t *pc_buff, \fBt_consoleTokHndl\fP *pt_tokHndl))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main handler for the system console interface\&. 

This file defines a set of functions that provide the tools for interacting with the operating system or user-space application via the console interface\&. The primary handler is a blocking thread named arb_console, which wakes any time a message is is received over the console via the device driver #drv_console\&. After waking, the thread validates the message by checking its first token against a list of basic kernel commands (sdl, dev, top)\&. If the token doesn't match, the entire message is routed to the user-space layer for further evaluation\&. After processing the message, the user-space layer returns processing back to arb_console with an indicator that lets the thread know if the message was handled properly\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (C) 2011-2013 Ryan M\&. Murphy <ryan\&.m\&.murphy\&.77\&. com> This program is free software: you can redistribute it and/ or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&. You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Ryan M\&. Murphy ryan.m.murphy.77@gmail.com
.RE
.PP
\fBDate:\fP
.RS 4
Jan, 14, 2013
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
