.TH "C:/arbitros/trunk/rtos/source/common/arb_main.c" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/rtos/source/common/arb_main.c \- 
.PP
Code entry point\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'arb_scheduler\&.h'\fP
.br
\fC#include 'arb_printf\&.h'\fP
.br
\fC#include 'utl_clocks\&.h'\fP
.br
\fC#include 'utl_pmic\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusr_appInit\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Code entry point\&. 

This file is responsible for OS initialization and starting the user space application\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (C) 2011-2013 Ryan M\&. Murphy <ryan\&.m\&.murphy\&.77\&. com> This program is free software: you can redistribute it and/ or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&. You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Ryan M\&. Murphy ryan.m.murphy.77@gmail.com
.RE
.PP
\fBDate:\fP
.RS 4
September 26, 2012
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
