.TH "MyCanvasBase" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyCanvasBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits GLCanvas\&.
.PP
Inherited by \fBCubeCanvas\fP, \fBXyPlotAccel\fP, \fBXyPlotGyro\fP, and \fBXyPlotMag\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
