.TH "XyPlotAccel" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XyPlotAccel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMyCanvasBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBInitGL\fP"
.br
.ti -1c
.RI "def \fBOnDraw\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
