.TH "C:/arbitros/trunk/libraries/sd/SdFat/ArduinoStream.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/ArduinoStream.h \- 
.PP
\fBArduinoInStream\fP and \fBArduinoOutStream\fP classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <bufstream\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBArduinoInStream\fP"
.br
.RI "\fIInput stream for Arduino \fBStream\fP objects\&. \fP"
.ti -1c
.RI "class \fBArduinoOutStream\fP"
.br
.RI "\fIOutput stream for Arduino \fBPrint\fP objects\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBArduinoInStream\fP and \fBArduinoOutStream\fP classes\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
