.TH "ArduinoOutStream" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArduinoOutStream \- 
.PP
Output stream for Arduino \fBPrint\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ArduinoStream\&.h>\fP
.PP
Inherits \fBostream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArduinoOutStream\fP (\fBPrint\fP &pr)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Output stream for Arduino \fBPrint\fP objects\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBArduinoOutStream\fP (\fBPrint\fP &pr)\fC [inline]\fP, \fC [explicit]\fP"
constructor
.PP
\fBParameters:\fP
.RS 4
\fIpr\fP \fBPrint\fP object for this \fBArduinoOutStream\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
