.TH "C:/arbitros/trunk/utilities/headers/xmega128A1/avr_compiler.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/utilities/headers/xmega128A1/avr_compiler.h \- 
.PP
This file implements some macros that makes the IAR C-compiler and avr-gcc work with the same code base for the AVR architecture\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   32000000UL"
.br
.RI "\fIDefine default CPU frequency, if this is not already defined\&. \fP"
.ti -1c
.RI "#define \fBAVR_ENTER_CRITICAL_REGION\fP()"
.br
.RI "\fIThis macro will protect the following code from interrupts\&. \fP"
.ti -1c
.RI "#define \fBAVR_LEAVE_CRITICAL_REGION\fP()   SREG = saved_sreg;"
.br
.RI "\fIThis macro must always be used in conjunction with AVR_ENTER_CRITICAL_REGION so the interrupts are enabled again\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This file implements some macros that makes the IAR C-compiler and avr-gcc work with the same code base for the AVR architecture\&. 

\fBDocumentation\fP
.RS 4
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme\&.html
.RE
.PP
\fBAuthor:\fP
.RS 4
Atmel Corporation: http://www.atmel.com 
.br
 Support email: avr@atmel.com
.RE
.PP
\fBRevision:\fP
.RS 4
2772 
.RE
.PP
\fBDate:\fP
.RS 4
2009-09-11 12:40:26 +0200 (fr, 11 sep 2009) 
.RE
.PP

.br
.PP
Copyright (c) 2008, Atmel Corporation All rights reserved\&.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.PP
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.PP
.PP
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.PP
.PP
.IP "3." 4
The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY ATMEL 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED\&. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define AVR_ENTER_CRITICAL_REGION()"
\fBValue:\fP
.PP
.nf
uint8_t volatile saved_sreg = SREG; \
                                     cli();
.fi
.PP
This macro will protect the following code from interrupts\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
