.TH "C:/arbitros/trunk/libraries/sd/SdFat/bufstream.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/bufstream.h \- 
.PP
\fBibufstream\fP and \fBobufstream\fP classes  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBibufstream\fP"
.br
.RI "\fIparse a char string \fP"
.ti -1c
.RI "class \fBobufstream\fP"
.br
.RI "\fIformat a char string \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBibufstream\fP and \fBobufstream\fP classes 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
