.TH "C:/arbitros/trunk/drivers/matlab/ins Directory Reference" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/drivers/matlab/ins Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccRollPitch\&.m\fP"
.br
.ti -1c
.RI "file \fBahrs\&.m\fP"
.br
.ti -1c
.RI "file \fBahrsSamples\&.m\fP"
.br
.ti -1c
.RI "file \fBcorrectAttitude\&.m\fP"
.br
.ti -1c
.RI "file \fBdcmNormalize\&.m\fP"
.br
.ti -1c
.RI "file \fBdcmUpdate\&.m\fP"
.br
.ti -1c
.RI "file \fBellipsoid_fit\&.m\fP"
.br
.ti -1c
.RI "file \fBerrorStateKalman\&.m\fP"
.br
.ti -1c
.RI "file \fBeulerAngles\&.m\fP"
.br
.ti -1c
.RI "file \fBmagHeading\&.m\fP"
.br
.ti -1c
.RI "file \fBmagPlot\&.m\fP"
.br
.ti -1c
.RI "file \fBphaseError\&.m\fP"
.br
.in -1c
