.TH "C:/arbitros/trunk/libraries/sd/SdFat Directory Reference" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBarduino\fP"
.br
.ti -1c
.RI "directory \fButility\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArduinoStream\&.h\fP"
.br
.RI "\fI\fBArduinoInStream\fP and \fBArduinoOutStream\fP classes\&. \fP"
.ti -1c
.RI "file \fBbufstream\&.h\fP"
.br
.RI "\fI\fBibufstream\fP and \fBobufstream\fP classes \fP"
.ti -1c
.RI "file \fBios\&.h\fP"
.br
.RI "\fI\fBios_base\fP and \fBios\fP classes \fP"
.ti -1c
.RI "file \fBiostream\&.h\fP"
.br
.RI "\fI\fBiostream\fP class \fP"
.ti -1c
.RI "file \fBistream\&.cpp\fP"
.br
.ti -1c
.RI "file \fBistream\&.h\fP"
.br
.RI "\fI\fBistream\fP class \fP"
.ti -1c
.RI "file \fBMinimumSerial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMinimumSerial\&.h\fP"
.br
.ti -1c
.RI "file \fBostream\&.cpp\fP"
.br
.ti -1c
.RI "file \fBostream\&.h\fP"
.br
.RI "\fI\fBostream\fP class \fP"
.ti -1c
.RI "file \fBSd2Card\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSd2Card\&.h\fP"
.br
.RI "\fI\fBSd2Card\fP class for V2 SD/SDHC cards\&. \fP"
.ti -1c
.RI "file \fBSdBaseFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSdBaseFile\&.h\fP"
.br
.RI "\fI\fBSdBaseFile\fP class\&. \fP"
.ti -1c
.RI "file \fBSdFat\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSdFat\&.h\fP"
.br
.RI "\fI\fBSdFat\fP class\&. \fP"
.ti -1c
.RI "file \fBSdFatConfig\&.h\fP"
.br
.RI "\fIconfiguration definitions \fP"
.ti -1c
.RI "file \fBSdFatmainpage\&.h\fP"
.br
.ti -1c
.RI "file \fBSdFatStructs\&.h\fP"
.br
.RI "\fIFAT file structures\&. \fP"
.ti -1c
.RI "file \fBSdFatUtil\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSdFatUtil\&.h\fP"
.br
.RI "\fIUseful utility functions\&. \fP"
.ti -1c
.RI "file \fBSdFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSdFile\&.h\fP"
.br
.RI "\fI\fBSdFile\fP class\&. \fP"
.ti -1c
.RI "file \fBSdInfo\&.h\fP"
.br
.ti -1c
.RI "file \fBSdStream\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSdStream\&.h\fP"
.br
.RI "\fI\fBfstream\fP, \fBifstream\fP, and \fBofstream\fP classes \fP"
.ti -1c
.RI "file \fBSdVolume\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSdVolume\&.h\fP"
.br
.RI "\fI\fBSdVolume\fP class\&. \fP"
.in -1c
