.TH "C:/arbitros/trunk/libraries/sd/project/atxmega128A1/sd Directory Reference" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/project/atxmega128A1/sd Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBRelease\fP"
.br
.in -1c
