.TH "C:/arbitros/trunk/libraries/sd/SdFat/utility Directory Reference" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/utility Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDigitalPin\&.h\fP"
.br
.RI "\fIFast Digital Pin functions\&. \fP"
.ti -1c
.RI "file \fBSoftSPI\&.h\fP"
.br
.RI "\fISoftware SPI\&. \fP"
.in -1c
