.TH "C:/arbitros/trunk/utilities/headers/xmega128A1 Directory Reference" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/utilities/headers/xmega128A1 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBavr_compiler\&.h\fP"
.br
.RI "\fIThis file implements some macros that makes the IAR C-compiler and avr-gcc work with the same code base for the AVR architecture\&. \fP"
.ti -1c
.RI "file \fButl_adc\&.h\fP"
.br
.ti -1c
.RI "file \fButl_clocks\&.h\fP"
.br
.ti -1c
.RI "file \fButl_dma\&.h\fP"
.br
.ti -1c
.RI "file \fButl_eeprom\&.h\fP"
.br
.ti -1c
.RI "file \fButl_gpio\&.h\fP"
.br
.ti -1c
.RI "file \fButl_pmic\&.h\fP"
.br
.ti -1c
.RI "file \fButl_spi\&.h\fP"
.br
.ti -1c
.RI "file \fButl_timer\&.h\fP"
.br
.ti -1c
.RI "file \fButl_twi\&.h\fP"
.br
.ti -1c
.RI "file \fButl_uart\&.h\fP"
.br
.ti -1c
.RI "file \fButl_watchDog\&.h\fP"
.br
.in -1c
