.TH "cache_t" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_t \- 
.PP
Cache for an SD data block\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdVolume\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBdata\fP [512]"
.br
.ti -1c
.RI "uint16_t \fBfat16\fP [256]"
.br
.ti -1c
.RI "uint32_t \fBfat32\fP [128]"
.br
.ti -1c
.RI "\fBdir_t\fP \fBdir\fP [16]"
.br
.ti -1c
.RI "\fBmbr_t\fP \fBmbr\fP"
.br
.ti -1c
.RI "\fBfat_boot_t\fP \fBfbs\fP"
.br
.ti -1c
.RI "\fBfat32_boot_t\fP \fBfbs32\fP"
.br
.ti -1c
.RI "\fBfat32_fsinfo_t\fP \fBfsinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cache for an SD data block\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t data[512]"
Used to access cached file data blocks\&. 
.SS "\fBdir_t\fP dir[16]"
Used to access cached directory entries\&. 
.SS "uint16_t fat16[256]"
Used to access cached FAT16 entries\&. 
.SS "uint32_t fat32[128]"
Used to access cached FAT32 entries\&. 
.SS "\fBfat_boot_t\fP fbs"
Used to access to a cached FAT boot sector\&. 
.SS "\fBfat32_boot_t\fP fbs32"
Used to access to a cached FAT32 boot sector\&. 
.SS "\fBfat32_fsinfo_t\fP fsinfo"
Used to access to a cached FAT32 FSINFO sector\&. 
.SS "\fBmbr_t\fP mbr"
Used to access a cached Master Boot Record\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
