.TH "CDCDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDCDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIADDescriptor\fP \fBiad\fP"
.br
.ti -1c
.RI "\fBInterfaceDescriptor\fP \fBcif\fP"
.br
.ti -1c
.RI "\fBCDCCSInterfaceDescriptor\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBCMFunctionalDescriptor\fP \fBcallManagement\fP"
.br
.ti -1c
.RI "\fBACMFunctionalDescriptor\fP \fBcontrolManagement\fP"
.br
.ti -1c
.RI "\fBCDCCSInterfaceDescriptor\fP \fBfunctionalDescriptor\fP"
.br
.ti -1c
.RI "\fBEndpointDescriptor\fP \fBcifin\fP"
.br
.ti -1c
.RI "\fBInterfaceDescriptor\fP \fBdif\fP"
.br
.ti -1c
.RI "\fBEndpointDescriptor\fP \fBin\fP"
.br
.ti -1c
.RI "\fBEndpointDescriptor\fP \fBout\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
