.TH "Client" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBconnect\fP (\fBIPAddress\fP ip, uint16_t port)=0"
.br
.ti -1c
.RI "virtual int \fBconnect\fP (const char *host, uint16_t port)=0"
.br
.ti -1c
.RI "virtual size_t \fBwrite\fP (uint8_t)=0"
.br
.ti -1c
.RI "virtual size_t \fBwrite\fP (const uint8_t *buf, size_t size)=0"
.br
.ti -1c
.RI "virtual int \fBavailable\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBread\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBread\fP (uint8_t *buf, size_t size)=0"
.br
.ti -1c
.RI "virtual int \fBpeek\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflush\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.ti -1c
.RI "virtual uint8_t \fBconnected\fP ()=0"
.br
.ti -1c
.RI "virtual \fBoperator bool\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "uint8_t * \fBrawIPAddress\fP (\fBIPAddress\fP &addr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
