.TH "ConfigDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBlen\fP"
.br
.ti -1c
.RI "u8 \fBdtype\fP"
.br
.ti -1c
.RI "u16 \fBclen\fP"
.br
.ti -1c
.RI "u8 \fBnumInterfaces\fP"
.br
.ti -1c
.RI "u8 \fBconfig\fP"
.br
.ti -1c
.RI "u8 \fBiconfig\fP"
.br
.ti -1c
.RI "u8 \fBattributes\fP"
.br
.ti -1c
.RI "u8 \fBmaxPower\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
