.TH "csd_t" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csd_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdInfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "csd1_t \fBv1\fP"
.br
.ti -1c
.RI "csd2_t \fBv2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
union of old and new style CSD register 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
