.TH "CSDV1" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSDV1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdInfo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBreserved1\fP: 6"
.br
.ti -1c
.RI "unsigned char \fBcsd_ver\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBtaac\fP"
.br
.ti -1c
.RI "unsigned char \fBnsac\fP"
.br
.ti -1c
.RI "unsigned char \fBtran_speed\fP"
.br
.ti -1c
.RI "unsigned char \fBccc_high\fP"
.br
.ti -1c
.RI "unsigned char \fBread_bl_len\fP: 4"
.br
.ti -1c
.RI "unsigned char \fBccc_low\fP: 4"
.br
.ti -1c
.RI "unsigned char \fBc_size_high\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBreserved2\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBdsr_imp\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBread_blk_misalign\fP:1"
.br
.ti -1c
.RI "unsigned char \fBwrite_blk_misalign\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBread_bl_partial\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBc_size_mid\fP"
.br
.ti -1c
.RI "unsigned char \fBvdd_r_curr_max\fP: 3"
.br
.ti -1c
.RI "unsigned char \fBvdd_r_curr_min\fP: 3"
.br
.ti -1c
.RI "unsigned char \fBc_size_low\fP:2"
.br
.ti -1c
.RI "unsigned char \fBc_size_mult_high\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBvdd_w_cur_max\fP: 3"
.br
.ti -1c
.RI "unsigned char \fBvdd_w_curr_min\fP: 3"
.br
.ti -1c
.RI "unsigned char \fBsector_size_high\fP: 6"
.br
.ti -1c
.RI "unsigned char \fBerase_blk_en\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBc_size_mult_low\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBwp_grp_size\fP: 7"
.br
.ti -1c
.RI "unsigned char \fBsector_size_low\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBwrite_bl_len_high\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBr2w_factor\fP: 3"
.br
.ti -1c
.RI "unsigned char \fBreserved3\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBwp_grp_enable\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBreserved4\fP: 5"
.br
.ti -1c
.RI "unsigned char \fBwrite_partial\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBwrite_bl_len_low\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBreserved5\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBfile_format\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBtmp_write_protect\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBperm_write_protect\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBcopy\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBfile_format_grp\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBalways1\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBcrc\fP: 7"
.br
.in -1c
.SH "Detailed Description"
.PP 
CSD for version 1\&.00 cards 
.SH "Field Documentation"
.PP 
.SS "unsigned char file_format_grp"
Indicates the file format on the card 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
