.TH "DeviceDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeviceDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBlen\fP"
.br
.ti -1c
.RI "u8 \fBdtype\fP"
.br
.ti -1c
.RI "u16 \fBusbVersion\fP"
.br
.ti -1c
.RI "u8 \fBdeviceClass\fP"
.br
.ti -1c
.RI "u8 \fBdeviceSubClass\fP"
.br
.ti -1c
.RI "u8 \fBdeviceProtocol\fP"
.br
.ti -1c
.RI "u8 \fBpacketSize0\fP"
.br
.ti -1c
.RI "u16 \fBidVendor\fP"
.br
.ti -1c
.RI "u16 \fBidProduct\fP"
.br
.ti -1c
.RI "u16 \fBdeviceVersion\fP"
.br
.ti -1c
.RI "u8 \fBiManufacturer\fP"
.br
.ti -1c
.RI "u8 \fBiProduct\fP"
.br
.ti -1c
.RI "u8 \fBiSerialNumber\fP"
.br
.ti -1c
.RI "u8 \fBbNumConfigurations\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
