.TH "C:/arbitros/trunk/libraries/sd/SdFat/utility/DigitalPin.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/utility/DigitalPin.h \- 
.PP
Fast Digital Pin functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <util/atomic\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBpin_map_t\fP"
.br
.RI "\fIstruct for mapping digital pins \fP"
.ti -1c
.RI "class \fBDigitalPin< PinNumber >\fP"
.br
.RI "\fIFast AVR digital port I/O\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbadPinNumber\fP (void) \fB__attribute__\fP((error('Pin number is too large or not a const ant')))"
.br
.ti -1c
.RI "\fBif\fP (address >(uint8_t *) 0X5F)"
.br
.ti -1c
.RI "\fBif\fP (level)"
.br
.ti -1c
.RI "\fBfastBitWriteSafe\fP (pinMap[pin]\&.port, pinMap[pin]\&.bit, level)"
.br
.ti -1c
.RI "\fBfastBitWriteSafe\fP (pinMap[pin]\&.ddr, pinMap[pin]\&.bit, mode)"
.br
.ti -1c
.RI "\fBfastDigitalWrite\fP (pin, level)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static uint8_t \fBbit\fP"
.br
.ti -1c
.RI "static uint8_t bool level uint8_t \fBoldSREG\fP"
.br
.ti -1c
.RI "\fBelse\fP"
.br
.ti -1c
.RI "static bool \fBlevel\fP"
.br
.ti -1c
.RI "static bool \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast Digital Pin functions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
