.TH "directoryEntry" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
directoryEntry \- 
.PP
FAT short directory entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdFatStructs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBname\fP [11]"
.br
.ti -1c
.RI "uint8_t \fBattributes\fP"
.br
.ti -1c
.RI "uint8_t \fBreservedNT\fP"
.br
.ti -1c
.RI "uint8_t \fBcreationTimeTenths\fP"
.br
.ti -1c
.RI "uint16_t \fBcreationTime\fP"
.br
.ti -1c
.RI "uint16_t \fBcreationDate\fP"
.br
.ti -1c
.RI "uint16_t \fBlastAccessDate\fP"
.br
.ti -1c
.RI "uint16_t \fBfirstClusterHigh\fP"
.br
.ti -1c
.RI "uint16_t \fBlastWriteTime\fP"
.br
.ti -1c
.RI "uint16_t \fBlastWriteDate\fP"
.br
.ti -1c
.RI "uint16_t \fBfirstClusterLow\fP"
.br
.ti -1c
.RI "uint32_t \fBfileSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAT short directory entry\&. 

Short means short 8\&.3 name, not the entry size\&.
.PP
Date Format\&. A FAT directory entry date stamp is a 16-bit field that is basically a date relative to the MS-DOS epoch of 01/01/1980\&. Here is the format (bit 0 is the LSB of the 16-bit word, bit 15 is the MSB of the 16-bit word):
.PP
Bits 9-15: Count of years from 1980, valid value range 0-127 inclusive (1980-2107)\&.
.PP
Bits 5-8: Month of year, 1 = January, valid value range 1-12 inclusive\&.
.PP
Bits 0-4: Day of month, valid value range 1-31 inclusive\&.
.PP
Time Format\&. A FAT directory entry time stamp is a 16-bit field that has a granularity of 2 seconds\&. Here is the format (bit 0 is the LSB of the 16-bit word, bit 15 is the MSB of the 16-bit word)\&.
.PP
Bits 11-15: Hours, valid value range 0-23 inclusive\&.
.PP
Bits 5-10: Minutes, valid value range 0-59 inclusive\&.
.PP
Bits 0-4: 2-second count, valid value range 0-29 inclusive (0 - 58 seconds)\&.
.PP
The valid time range is from Midnight 00:00:00 to 23:59:58\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t attributes"
Entry attributes\&.
.PP
The upper two bits of the attribute byte are reserved and should always be set to 0 when a file is created and never modified or looked at after that\&. See defines that begin with DIR_ATT_\&. 
.SS "uint16_t creationDate"
Date file was created\&. 
.SS "uint16_t creationTime"
Time file was created\&. 
.SS "uint8_t creationTimeTenths"
The granularity of the seconds part of creationTime is 2 seconds so this field is a count of tenths of a second and its valid value range is 0-199 inclusive\&. (WHG note - seems to be hundredths) 
.SS "uint32_t fileSize"
32-bit unsigned holding this file's size in bytes\&. 
.SS "uint16_t firstClusterHigh"
High word of this entry's first cluster number (always 0 for a FAT12 or FAT16 volume)\&. 
.SS "uint16_t firstClusterLow"
Low word of this entry's first cluster number\&. 
.SS "uint16_t lastAccessDate"
Last access date\&. Note that there is no last access time, only a date\&. This is the date of last read or write\&. In the case of a write, this should be set to the same date as lastWriteDate\&. 
.SS "uint16_t lastWriteDate"
Date of last write\&. \fBFile\fP creation is considered a write\&. 
.SS "uint16_t lastWriteTime"
Time of last write\&. \fBFile\fP creation is considered a write\&. 
.SS "uint8_t name[11]"
Short 8\&.3 name\&.
.PP
The first eight bytes contain the file name with blank fill\&. The last three bytes contain the file extension with blank fill\&. 
.SS "uint8_t reservedNT"
Reserved for use by Windows NT\&. Set value to 0 when a file is created and never modify or look at it after that\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
