.TH "EndpointDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EndpointDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBlen\fP"
.br
.ti -1c
.RI "u8 \fBdtype\fP"
.br
.ti -1c
.RI "u8 \fBaddr\fP"
.br
.ti -1c
.RI "u8 \fBattr\fP"
.br
.ti -1c
.RI "u16 \fBpacketSize\fP"
.br
.ti -1c
.RI "u8 \fBinterval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
