.TH "fat32_fsinfo" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fat32_fsinfo \- 
.PP
FSINFO sector for a FAT32 volume\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdFatStructs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBleadSignature\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved1\fP [480]"
.br
.ti -1c
.RI "uint32_t \fBstructSignature\fP"
.br
.ti -1c
.RI "uint32_t \fBfreeCount\fP"
.br
.ti -1c
.RI "uint32_t \fBnextFree\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved2\fP [12]"
.br
.ti -1c
.RI "uint8_t \fBtailSignature\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
FSINFO sector for a FAT32 volume\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t freeCount"
Contains the last known free cluster count on the volume\&. If the value is 0xFFFFFFFF, then the free count is unknown and must be computed\&. Any other value can be used, but is not necessarily correct\&. It should be range checked at least to make sure it is <= volume cluster count\&. 
.SS "uint32_t leadSignature"
must be 0X52, 0X52, 0X61, 0X41 
.SS "uint32_t nextFree"
This is a hint for the FAT driver\&. It indicates the cluster number at which the driver should start looking for free clusters\&. If the value is 0xFFFFFFFF, then there is no hint and the driver should start looking at cluster 2\&. 
.SS "uint8_t reserved1[480]"
must be zero 
.SS "uint8_t reserved2[12]"
must be zero 
.SS "uint32_t structSignature"
must be 0X72, 0X72, 0X41, 0X61 
.SS "uint8_t tailSignature[4]"
must be 0X00, 0X00, 0X55, 0XAA 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
