.TH "FatPos_t" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FatPos_t \- 
.PP
internal type for istream do not use in user apps  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdBaseFile\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBposition\fP"
.br
.ti -1c
.RI "uint32_t \fBcluster\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
internal type for istream do not use in user apps 
.SH "Field Documentation"
.PP 
.SS "uint32_t cluster"
cluster for position 
.SS "uint32_t position"
stream position 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
