.TH "fstream" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fstream \- 
.PP
SD file input/output stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdStream\&.h>\fP
.PP
Inherits \fBiostream\fP, and \fBSdStreamBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfstream\fP (const char *path, \fBopenmode\fP mode=\fBin\fP|\fBout\fP)"
.br
.ti -1c
.RI "void \fBclear\fP (\fBiostate\fP state=\fBgoodbit\fP)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBopen\fP (const char *path, \fBopenmode\fP mode=\fBin\fP|\fBout\fP)"
.br
.ti -1c
.RI "bool \fBis_open\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
SD file input/output stream\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBfstream\fP (const char *path, \fBopenmode\fPmode = \fC\fBin\fP | \fBout\fP\fP)\fC [inline]\fP, \fC [explicit]\fP"
Constructor with open
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP path to open 
.br
\fImode\fP open mode 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void clear (\fBiostate\fPstate = \fC\fBgoodbit\fP\fP)\fC [inline]\fP"
Clear state and writeError 
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP new state for stream 
.RE
.PP

.SS "void close ()\fC [inline]\fP"
Close a file and force cached data and directory information to be written to the storage device\&. 
.SS "bool is_open ()\fC [inline]\fP"
\fBReturns:\fP
.RS 4
True if stream is open else false\&. 
.RE
.PP

.SS "void open (const char *path, \fBopenmode\fPmode = \fC\fBin\fP | \fBout\fP\fP)\fC [inline]\fP"
Open a fstream 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP file to open 
.br
\fImode\fP open mode
.RE
.PP
Valid open modes are (at end, \fBios::ate\fP, and/or \fBios::binary\fP may be added):
.PP
\fBios::in\fP - Open file for reading\&.
.PP
\fBios::out\fP or \fBios::out\fP | \fBios::trunc\fP - Truncate to 0 length, if existent, or create a file for writing only\&.
.PP
\fBios::app\fP or \fBios::out\fP | \fBios::app\fP - Append; open or create file for writing at end-of-file\&.
.PP
\fBios::in\fP | \fBios::out\fP - Open file for update (reading and writing)\&.
.PP
\fBios::in\fP | \fBios::out\fP | \fBios::trunc\fP - Truncate to zero length, if existent, or create file for update\&.
.PP
\fBios::in\fP | \fBios::app\fP or \fBios::in\fP | \fBios::out\fP | \fBios::app\fP - Append; open or create text file for update, writing at end of file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
