.TH "HIDDescDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HIDDescDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBlen\fP"
.br
.ti -1c
.RI "u8 \fBdtype\fP"
.br
.ti -1c
.RI "u8 \fBaddr\fP"
.br
.ti -1c
.RI "u8 \fBversionL\fP"
.br
.ti -1c
.RI "u8 \fBversionH\fP"
.br
.ti -1c
.RI "u8 \fBcountry\fP"
.br
.ti -1c
.RI "u8 \fBdesctype\fP"
.br
.ti -1c
.RI "u8 \fBdescLenL\fP"
.br
.ti -1c
.RI "u8 \fBdescLenH\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
