.TH "IADDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IADDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBlen\fP"
.br
.ti -1c
.RI "u8 \fBdtype\fP"
.br
.ti -1c
.RI "u8 \fBfirstInterface\fP"
.br
.ti -1c
.RI "u8 \fBinterfaceCount\fP"
.br
.ti -1c
.RI "u8 \fBfunctionClass\fP"
.br
.ti -1c
.RI "u8 \fBfuntionSubClass\fP"
.br
.ti -1c
.RI "u8 \fBfunctionProtocol\fP"
.br
.ti -1c
.RI "u8 \fBiInterface\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
