.TH "ibufstream" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ibufstream \- 
.PP
parse a char string  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bufstream\&.h>\fP
.PP
Inherits \fBistream\fP\&.
.PP
Inherited by \fBArduinoInStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBibufstream\fP ()"
.br
.ti -1c
.RI "\fBibufstream\fP (const char *str)"
.br
.ti -1c
.RI "void \fBinit\fP (const char *str)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
parse a char string 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBibufstream\fP ()\fC [inline]\fP"
Constructor 
.SS "\fBibufstream\fP (const char *str)\fC [inline]\fP, \fC [explicit]\fP"
Constructor 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP pointer to string to be parsed Warning: The string will not be copied so must stay in scope\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void init (const char *str)\fC [inline]\fP"
Initialize an ibufstream 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP pointer to string to be parsed Warning: The string will not be copied so must stay in scope\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
