.TH "InterfaceDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBlen\fP"
.br
.ti -1c
.RI "u8 \fBdtype\fP"
.br
.ti -1c
.RI "u8 \fBnumber\fP"
.br
.ti -1c
.RI "u8 \fBalternate\fP"
.br
.ti -1c
.RI "u8 \fBnumEndpoints\fP"
.br
.ti -1c
.RI "u8 \fBinterfaceClass\fP"
.br
.ti -1c
.RI "u8 \fBinterfaceSubClass\fP"
.br
.ti -1c
.RI "u8 \fBprotocol\fP"
.br
.ti -1c
.RI "u8 \fBiInterface\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
