.TH "ios" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ios \- 
.PP
Error and state information for all streams\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ios\&.h>\fP
.PP
Inherits \fBios_base\fP\&.
.PP
Inherited by \fBistream\fP\fC [virtual]\fP, \fBostream\fP\fC [virtual]\fP, and \fBSdStreamBase\fP\fC [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBios\fP ()"
.br
.ti -1c
.RI "\fBoperator const void *\fP () const "
.br
.ti -1c
.RI "bool \fBoperator!\fP () const "
.br
.ti -1c
.RI "\fBiostate\fP \fBrdstate\fP () const "
.br
.ti -1c
.RI "bool \fBgood\fP () const "
.br
.ti -1c
.RI "bool \fBeof\fP () const "
.br
.ti -1c
.RI "bool \fBfail\fP () const "
.br
.ti -1c
.RI "bool \fBbad\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP (\fBiostate\fP state=\fBgoodbit\fP)"
.br
.ti -1c
.RI "void \fBsetstate\fP (\fBiostate\fP state)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Error and state information for all streams\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBios\fP ()\fC [inline]\fP"
Create ios with no error flags set 
.SH "Member Function Documentation"
.PP 
.SS "bool bad () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
true if bad bit is set else false\&. 
.RE
.PP

.SS "void clear (\fBiostate\fPstate = \fC\fBgoodbit\fP\fP)\fC [inline]\fP"
Clear iostate bits\&.
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP The flags you want to set after clearing all flags\&. 
.RE
.PP

.SS "bool eof () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
true if end of file has been reached else false\&.
.RE
.PP
Warning: An empty file returns false before the first read\&.
.PP
Moral: \fBeof()\fP is only useful in combination with \fBfail()\fP, to find out whether EOF was the cause for failure 
.SS "bool fail () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
true if any iostate bit other than eof are set else false\&. 
.RE
.PP

.SS "bool good () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
True if no iostate flags are set else false\&. 
.RE
.PP

.SS "operator const void * () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
null pointer if \fBfail()\fP is true\&. 
.RE
.PP

.SS "bool operator! () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
true if \fBfail()\fP else false\&. 
.RE
.PP

.SS "\fBiostate\fP rdstate () const\fC [inline]\fP"
\fBReturns:\fP
.RS 4
The iostate flags for this file\&. 
.RE
.PP

.SS "void setstate (\fBiostate\fPstate)\fC [inline]\fP"
Set iostate bits\&.
.PP
\fBParameters:\fP
.RS 4
\fIstate\fP Bitts to set\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
