.TH "C:/arbitros/trunk/libraries/sd/SdFat/ios.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/ios.h \- 
.PP
\fBios_base\fP and \fBios\fP classes  

.SH SYNOPSIS
.br
.PP
\fC#include <SdBaseFile\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBios_base\fP"
.br
.RI "\fIBase class for all streams\&. \fP"
.ti -1c
.RI "class \fBios\fP"
.br
.RI "\fIError and state information for all streams\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBios_base\fP & \fBboolalpha\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBdec\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBhex\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBinternal\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBleft\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBnoboolalpha\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBnoshowbase\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBnoshowpoint\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBnoshowpos\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBnoskipws\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBnouppercase\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBoct\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBright\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBshowbase\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBshowpos\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBshowpoint\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBskipws\fP (\fBios_base\fP &str)"
.br
.ti -1c
.RI "\fBios_base\fP & \fBuppercase\fP (\fBios_base\fP &str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBios_base\fP and \fBios\fP classes 


.SH "Function Documentation"
.PP 
.SS "\fBios_base\fP& boolalpha (\fBios_base\fP &str)\fC [inline]\fP"
function for boolalpha manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& dec (\fBios_base\fP &str)\fC [inline]\fP"
function for dec manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& hex (\fBios_base\fP &str)\fC [inline]\fP"
function for hex manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& internal (\fBios_base\fP &str)\fC [inline]\fP"
function for internal manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& left (\fBios_base\fP &str)\fC [inline]\fP"
function for left manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& noboolalpha (\fBios_base\fP &str)\fC [inline]\fP"
function for noboolalpha manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& noshowbase (\fBios_base\fP &str)\fC [inline]\fP"
function for noshowbase manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& noshowpoint (\fBios_base\fP &str)\fC [inline]\fP"
function for noshowpoint manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& noshowpos (\fBios_base\fP &str)\fC [inline]\fP"
function for noshowpos manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& noskipws (\fBios_base\fP &str)\fC [inline]\fP"
function for noskipws manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& nouppercase (\fBios_base\fP &str)\fC [inline]\fP"
function for nouppercase manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& oct (\fBios_base\fP &str)\fC [inline]\fP"
function for oct manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& right (\fBios_base\fP &str)\fC [inline]\fP"
function for right manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& showbase (\fBios_base\fP &str)\fC [inline]\fP"
function for showbase manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& showpoint (\fBios_base\fP &str)\fC [inline]\fP"
function for showpoint manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& showpos (\fBios_base\fP &str)\fC [inline]\fP"
function for showpos manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& skipws (\fBios_base\fP &str)\fC [inline]\fP"
function for skipws manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBios_base\fP& uppercase (\fBios_base\fP &str)\fC [inline]\fP"
function for uppercase manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
