.TH "C:/arbitros/trunk/libraries/sd/SdFat/iostream.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/iostream.h \- 
.PP
\fBiostream\fP class  

.SH SYNOPSIS
.br
.PP
\fC#include <istream\&.h>\fP
.br
\fC#include <ostream\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsetfill\fP"
.br
.RI "\fItype for setfill manipulator \fP"
.ti -1c
.RI "struct \fBsetprecision\fP"
.br
.RI "\fItype for setprecision manipulator \fP"
.ti -1c
.RI "struct \fBsetw\fP"
.br
.RI "\fItype for setw manipulator \fP"
.ti -1c
.RI "class \fBiostream\fP"
.br
.RI "\fIInput/Output stream\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBistream\fP & \fBws\fP (\fBistream\fP &is)"
.br
.ti -1c
.RI "\fBostream\fP & \fBendl\fP (\fBostream\fP &os)"
.br
.ti -1c
.RI "\fBostream\fP & \fBflush\fP (\fBostream\fP &os)"
.br
.ti -1c
.RI "\fBostream\fP & \fBoperator<<\fP (\fBostream\fP &os, const \fBsetfill\fP &arg)"
.br
.ti -1c
.RI "\fBistream\fP & \fBoperator>>\fP (\fBistream\fP &obj, const \fBsetfill\fP &arg)"
.br
.ti -1c
.RI "\fBostream\fP & \fBoperator<<\fP (\fBostream\fP &os, const \fBsetprecision\fP &arg)"
.br
.ti -1c
.RI "\fBistream\fP & \fBoperator>>\fP (\fBistream\fP &is, const \fBsetprecision\fP &arg)"
.br
.ti -1c
.RI "\fBostream\fP & \fBoperator<<\fP (\fBostream\fP &os, const \fBsetw\fP &arg)"
.br
.ti -1c
.RI "\fBistream\fP & \fBoperator>>\fP (\fBistream\fP &is, const \fBsetw\fP &arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBiostream\fP class 


.SH "Function Documentation"
.PP 
.SS "\fBostream\fP& endl (\fBostream\fP &os)\fC [inline]\fP"
insert endline 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP The \fBStream\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBostream\fP& flush (\fBostream\fP &os)\fC [inline]\fP"
flush manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP The stream 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SS "\fBostream\fP& operator<< (\fBostream\fP &os, const \fBsetfill\fP &arg)\fC [inline]\fP"
setfill manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP the stream 
.br
\fIarg\fP set setfill object 
.RE
.PP
\fBReturns:\fP
.RS 4
the stream 
.RE
.PP

.SS "\fBostream\fP& operator<< (\fBostream\fP &os, const \fBsetprecision\fP &arg)\fC [inline]\fP"
setprecision manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP the stream 
.br
\fIarg\fP set setprecision object 
.RE
.PP
\fBReturns:\fP
.RS 4
the stream 
.RE
.PP

.SS "\fBostream\fP& operator<< (\fBostream\fP &os, const \fBsetw\fP &arg)\fC [inline]\fP"
setw manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP the stream 
.br
\fIarg\fP set setw object 
.RE
.PP
\fBReturns:\fP
.RS 4
the stream 
.RE
.PP

.SS "\fBistream\fP& operator>> (\fBistream\fP &obj, const \fBsetfill\fP &arg)\fC [inline]\fP"
setfill manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP the stream 
.br
\fIarg\fP set setfill object 
.RE
.PP
\fBReturns:\fP
.RS 4
the stream 
.RE
.PP

.SS "\fBistream\fP& operator>> (\fBistream\fP &is, const \fBsetprecision\fP &arg)\fC [inline]\fP"
setprecision manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIis\fP the stream 
.br
\fIarg\fP set setprecision object 
.RE
.PP
\fBReturns:\fP
.RS 4
the stream 
.RE
.PP

.SS "\fBistream\fP& operator>> (\fBistream\fP &is, const \fBsetw\fP &arg)\fC [inline]\fP"
setw manipulator 
.PP
\fBParameters:\fP
.RS 4
\fIis\fP the stream 
.br
\fIarg\fP set setw object 
.RE
.PP
\fBReturns:\fP
.RS 4
the stream 
.RE
.PP

.SS "\fBistream\fP& ws (\fBistream\fP &is)\fC [inline]\fP"
Skip white space 
.PP
\fBParameters:\fP
.RS 4
\fIis\fP the \fBStream\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
The stream 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
