.TH "iostream" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iostream \- 
.PP
Input/Output stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iostream\&.h>\fP
.PP
Inherits \fBistream\fP, and \fBostream\fP\&.
.PP
Inherited by \fBfstream\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Input/Output stream\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
