.TH "IPAddress" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrintable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIPAddress\fP (uint8_t first_octet, uint8_t second_octet, uint8_t third_octet, uint8_t fourth_octet)"
.br
.ti -1c
.RI "\fBIPAddress\fP (uint32_t address)"
.br
.ti -1c
.RI "\fBIPAddress\fP (const uint8_t *address)"
.br
.ti -1c
.RI "\fBoperator uint32_t\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBIPAddress\fP &addr)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const uint8_t *addr)"
.br
.ti -1c
.RI "uint8_t \fBoperator[]\fP (int index) const "
.br
.ti -1c
.RI "uint8_t & \fBoperator[]\fP (int index)"
.br
.ti -1c
.RI "\fBIPAddress\fP & \fBoperator=\fP (const uint8_t *address)"
.br
.ti -1c
.RI "\fBIPAddress\fP & \fBoperator=\fP (uint32_t address)"
.br
.ti -1c
.RI "virtual size_t \fBprintTo\fP (\fBPrint\fP &p) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEthernetClass\fP"
.br
.ti -1c
.RI "class \fBUDP\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBServer\fP"
.br
.ti -1c
.RI "class \fBDhcpClass\fP"
.br
.ti -1c
.RI "class \fBDNSClient\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
