.TH "MinimumSerial" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinimumSerial \- 
.PP
mini serial class for the SdFat library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MinimumSerial\&.h>\fP
.PP
Inherits \fBPrint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbegin\fP (unsigned long)"
.br
.ti -1c
.RI "int \fBread\fP ()"
.br
.ti -1c
.RI "size_t \fBwrite\fP (uint8_t b)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
mini serial class for the SdFat library\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
