.TH "MSCDescriptor" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSCDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBInterfaceDescriptor\fP \fBmsc\fP"
.br
.ti -1c
.RI "\fBEndpointDescriptor\fP \fBin\fP"
.br
.ti -1c
.RI "\fBEndpointDescriptor\fP \fBout\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
