.TH "obufstream" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obufstream \- 
.PP
format a char string  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bufstream\&.h>\fP
.PP
Inherits \fBostream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBobufstream\fP ()"
.br
.ti -1c
.RI "\fBobufstream\fP (char *\fBbuf\fP, size_t size)"
.br
.ti -1c
.RI "void \fBinit\fP (char *\fBbuf\fP, size_t size)"
.br
.ti -1c
.RI "char * \fBbuf\fP ()"
.br
.ti -1c
.RI "size_t \fBlength\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
format a char string 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBobufstream\fP ()\fC [inline]\fP"
constructor 
.SS "\fBobufstream\fP (char *buf, size_tsize)\fC [inline]\fP"
Constructor 
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP buffer for formatted string 
.br
\fIsize\fP buffer size 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "char* buf ()\fC [inline]\fP"
\fBReturns:\fP
.RS 4
a pointer to the buffer 
.RE
.PP

.SS "void init (char *buf, size_tsize)\fC [inline]\fP"
Initialize an obufstream 
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP buffer for formatted string 
.br
\fIsize\fP buffer size 
.RE
.PP

.SS "size_t length ()\fC [inline]\fP"
\fBReturns:\fP
.RS 4
the length of the formatted string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
