.TH "C:/arbitros/trunk/libraries/sd/SdFat/ostream.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/ostream.h \- 
.PP
\fBostream\fP class  

.SH SYNOPSIS
.br
.PP
\fC#include <ios\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpgm\fP"
.br
.RI "\fItype for string in flash \fP"
.ti -1c
.RI "class \fBostream\fP"
.br
.RI "\fIOutput \fBStream\fP\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBpstr\fP(str)   \fBpgm\fP(\fBPSTR\fP(str))"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBostream\fP class 


.SH "Macro Definition Documentation"
.PP 
.SS "#define pstr(str)   \fBpgm\fP(\fBPSTR\fP(str))"
macro for flash inserter 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
