.TH "pgm" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgm \- 
.PP
type for string in flash  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ostream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpgm\fP (char *str)"
.br
.ti -1c
.RI "\fBpgm\fP (const char *str)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
type for string in flash 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBpgm\fP (char *str)\fC [inline]\fP, \fC [explicit]\fP"
constructor 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP initializer for pointer\&. 
.RE
.PP

.SS "\fBpgm\fP (const char *str)\fC [inline]\fP, \fC [explicit]\fP"
constructor 
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP initializer for pointer\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "char* ptr"
Pointer to flash string 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
