.TH "pin_map_t" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pin_map_t \- 
.PP
struct for mapping digital pins  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DigitalPin\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile uint8_t * \fBddr\fP"
.br
.ti -1c
.RI "volatile uint8_t * \fBpin\fP"
.br
.ti -1c
.RI "volatile uint8_t * \fBport\fP"
.br
.ti -1c
.RI "uint8_t \fBbit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct for mapping digital pins 
.SH "Field Documentation"
.PP 
.SS "uint8_t bit"
bit number for this pin 
.SS "volatile uint8_t* ddr"
address of DDR for this pin 
.SS "volatile uint8_t* pin"
address of PIN for this pin 
.SS "volatile uint8_t* port"
address of PORT for this pin 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
