.TH "Printable" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Printable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Printable\&.h>\fP
.PP
Inherited by \fBIPAddress\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual size_t \fBprintTo\fP (\fBPrint\fP &p) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPrintable\fP class provides a way for new classes to allow themselves to be printed\&. By deriving from \fBPrintable\fP and implementing the printTo method, it will then be possible for users to print out instances of this class by passing them into the usual Print::print and Print::println methods\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
