.TH "SDClass" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDClass \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBbegin\fP (uint8_t csPin=\fBSD_CHIP_SELECT_PIN\fP)"
.br
.ti -1c
.RI "\fBFile\fP \fBopen\fP (const char *filename, uint8_t mode=FILE_READ)"
.br
.ti -1c
.RI "boolean \fBexists\fP (char *filepath)"
.br
.ti -1c
.RI "boolean \fBmkdir\fP (char *filepath)"
.br
.ti -1c
.RI "boolean \fBremove\fP (char *filepath)"
.br
.ti -1c
.RI "boolean \fBrmdir\fP (char *filepath)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFile\fP"
.br
.ti -1c
.RI "boolean \fBcallback_openPath\fP (\fBSdFile\fP &, char *, boolean, void *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
