.TH "C:/arbitros/trunk/libraries/sd/SdFat/SdFat.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/SdFat.h \- 
.PP
\fBSdFat\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <SdFile\&.h>\fP
.br
\fC#include <SdStream\&.h>\fP
.br
\fC#include <ArduinoStream\&.h>\fP
.br
\fC#include <MinimumSerial\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSdFat\fP"
.br
.RI "\fIIntegration class for the SdFat library\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSD_FAT_VERSION\fP   20130629"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSdFat\fP class\&. 

\fBSd2Card\fP class for V2 SD/SDHC cards\&.
.PP
error if old IDE 
.SH "Macro Definition Documentation"
.PP 
.SS "#define SD_FAT_VERSION   20130629"
\fBSdFat\fP version YYYYMMDD 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
