.TH "C:/arbitros/trunk/libraries/sd/SdFat/SdFile.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/SdFile.h \- 
.PP
\fBSdFile\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <SdBaseFile\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSdFile\fP"
.br
.RI "\fI\fBSdBaseFile\fP with \fBPrint\fP\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSdFile\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSdFile\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
