.TH "C:/arbitros/trunk/libraries/sd/SdFat/SdStream.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/SdStream.h \- 
.PP
\fBfstream\fP, \fBifstream\fP, and \fBofstream\fP classes  

.SH SYNOPSIS
.br
.PP
\fC#include <SdBaseFile\&.h>\fP
.br
\fC#include <iostream\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSdStreamBase\fP"
.br
.RI "\fIBase class for SD streams\&. \fP"
.ti -1c
.RI "class \fBfstream\fP"
.br
.RI "\fISD file input/output stream\&. \fP"
.ti -1c
.RI "class \fBifstream\fP"
.br
.RI "\fISD file input stream\&. \fP"
.ti -1c
.RI "class \fBofstream\fP"
.br
.RI "\fISD card output stream\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBfstream\fP, \fBifstream\fP, and \fBofstream\fP classes 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
