.TH "SdStreamBase" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SdStreamBase \- 
.PP
Base class for SD streams\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SdStream\&.h>\fP
.PP
Inherits \fBSdBaseFile\fP, and \fBios\fP\&.
.PP
Inherited by \fBfstream\fP\fC [private]\fP, \fBifstream\fP\fC [private]\fP, and \fBofstream\fP\fC [private]\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class for SD streams\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
