.TH "C:/arbitros/trunk/libraries/sd/SdFat/SdVolume.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/SdVolume.h \- 
.PP
\fBSdVolume\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <SdFatConfig\&.h>\fP
.br
\fC#include <Sd2Card\&.h>\fP
.br
\fC#include <SdFatStructs\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBcache_t\fP"
.br
.RI "\fICache for an SD data block\&. \fP"
.ti -1c
.RI "class \fBSdVolume\fP"
.br
.RI "\fIAccess FAT16 and FAT32 volumes on SD and SDHC cards\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBSdVolume\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
