.TH "C:/arbitros/trunk/libraries/sd/SdFat/utility/SoftSPI.h" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/arbitros/trunk/libraries/sd/SdFat/utility/SoftSPI.h \- 
.PP
Software SPI\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <DigitalPin\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSoftSPI< MisoPin, MosiPin, SckPin, Mode >\fP"
.br
.RI "\fIFast software SPI\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBnop\fP   asm volatile ('nop\\n\\t')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const bool \fBMISO_MODE\fP = false"
.br
.ti -1c
.RI "const bool \fBMISO_LEVEL\fP = false"
.br
.ti -1c
.RI "const bool \fBMOSI_MODE\fP = true"
.br
.ti -1c
.RI "const bool \fBSCK_MODE\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Software SPI\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
