.TH "Stream" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrint\fP\&.
.PP
Inherited by \fBClient\fP, \fBFile\fP, \fBHardwareSerial\fP, and \fBUDP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBavailable\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBread\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBpeek\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflush\fP ()=0"
.br
.ti -1c
.RI "void \fBsetTimeout\fP (unsigned long timeout)"
.br
.ti -1c
.RI "bool \fBfind\fP (char *target)"
.br
.ti -1c
.RI "bool \fBfind\fP (char *target, size_t length)"
.br
.ti -1c
.RI "bool \fBfindUntil\fP (char *target, char *terminator)"
.br
.ti -1c
.RI "bool \fBfindUntil\fP (char *target, size_t targetLen, char *terminate, size_t termLen)"
.br
.ti -1c
.RI "long \fBparseInt\fP ()"
.br
.ti -1c
.RI "float \fBparseFloat\fP ()"
.br
.ti -1c
.RI "size_t \fBreadBytes\fP (char *buffer, size_t length)"
.br
.ti -1c
.RI "size_t \fBreadBytesUntil\fP (char terminator, char *buffer, size_t length)"
.br
.ti -1c
.RI "String \fBreadString\fP ()"
.br
.ti -1c
.RI "String \fBreadStringUntil\fP (char terminator)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "long \fBparseInt\fP (char skipChar)"
.br
.ti -1c
.RI "float \fBparseFloat\fP (char skipChar)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
