.TH "t_adcChanConf" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_adcChanConf \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBc_posPin\fP"
.br
.ti -1c
.RI "uint8_t \fBc_negPin\fP"
.br
.ti -1c
.RI "t_inputMode \fBt_inMode\fP"
.br
.ti -1c
.RI "t_diffGain \fBt_gain\fP"
.br
.ti -1c
.RI "bool \fBb_enableInt\fP"
.br
.ti -1c
.RI "void(* \fBpf_funPtr\fP )(int16_t s_sample)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
