.TH "t_adcModConf" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_adcModConf \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_convMode \fBt_mode\fP"
.br
.ti -1c
.RI "t_mesResolution \fBt_res\fP"
.br
.ti -1c
.RI "t_refVoltage \fBt_ref\fP"
.br
.ti -1c
.RI "t_refClock \fBt_clock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
