.TH "t_chanHandle" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_chanHandle \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_adcModuleId \fBt_module\fP"
.br
.ti -1c
.RI "t_chanId \fBt_id\fP"
.br
.ti -1c
.RI "ADC_CH_t * \fBpt_chan\fP"
.br
.ti -1c
.RI "int16_t \fBs_adcSample\fP"
.br
.ti -1c
.RI "void(* \fBpf_funPtr\fP )(int16_t s_sample)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
