.TH "t_consoleDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_consoleDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_SEMHANDLE \fBt_rxMutex\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_txMutex\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_rxBlockingSem\fP"
.br
.ti -1c
.RI "t_BUFFHANDLE \fBt_rxBuffer\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.ti -1c
.RI "t_UARTHNDL \fBt_uHandle\fP"
.br
.ti -1c
.RI "bool \fBb_rxActive\fP"
.br
.ti -1c
.RI "int8_t \fBc_cmdPromptColor\fP"
.br
.ti -1c
.RI "int8_t \fBc_fgColor\fP"
.br
.ti -1c
.RI "char \fBac_dirName\fP [CONSOLE_MAX_TOKEN_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
