.TH "t_consoleObject" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_consoleObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_THRDHANDLE \fBt_consoleThread\fP"
.br
.ti -1c
.RI "t_DEVHANDLE \fBt_consoleHndl\fP"
.br
.ti -1c
.RI "t_DEVHANDLE \fBt_sdHndl\fP"
.br
.ti -1c
.RI "bool(* \fBpf_funPtr\fP )(t_DEVHANDLE t_consoleHndl, int8_t *pc_buff, \fBt_consoleTokHndl\fP *pt_tokHndl)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
