.TH "t_custChar" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_custChar \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBc_address\fP"
.br
.ti -1c
.RI "uint8_t \fBac_bitMap\fP [8]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
