.TH "t_devHandle" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_devHandle \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_device\fP * \fBpt_dev\fP"
.br
.ti -1c
.RI "void * \fBpv_privateData\fP"
.br
.ti -1c
.RI "uint8_t \fBc_flags\fP"
.br
.ti -1c
.RI "uint32_t \fBi_pos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
