.TH "t_deviceOperations" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_deviceOperations \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_error(* \fBpf_open\fP )(t_DEVHANDLE \fBt_devHandle\fP)"
.br
.ti -1c
.RI "int16_t(* \fBpf_read\fP )(t_DEVHANDLE \fBt_devHandle\fP, int8_t *pc_buff, uint16_t s_size)"
.br
.ti -1c
.RI "int16_t(* \fBpf_write\fP )(t_DEVHANDLE \fBt_devHandle\fP, int8_t *pc_buff, uint16_t s_size)"
.br
.ti -1c
.RI "int32_t(* \fBpf_ioctl\fP )(t_DEVHANDLE \fBt_devHandle\fP, uint16_t s_command, int32_t i_arguments)"
.br
.ti -1c
.RI "t_error(* \fBpf_close\fP )(t_DEVHANDLE \fBt_devHandle\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
