.TH "t_device" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_device \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_deviceId \fBt_devId\fP"
.br
.ti -1c
.RI "int8_t \fBac_deviceName\fP [MAX_DEVICE_NAME_BYTES]"
.br
.ti -1c
.RI "int8_t \fBc_numDevHandles\fP"
.br
.ti -1c
.RI "\fBt_deviceOperations\fP * \fBpt_devOps\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
