.TH "t_dmaChanConfig" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_dmaChanConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t * \fBpi_srcAddress\fP"
.br
.ti -1c
.RI "uint32_t * \fBpi_destAddress\fP"
.br
.ti -1c
.RI "t_dmaAddressDirection \fBt_srcAddDir\fP"
.br
.ti -1c
.RI "t_dmaAddressDirection \fBt_destAddDir\fP"
.br
.ti -1c
.RI "t_dmaAddressReload \fBt_srcAddReload\fP"
.br
.ti -1c
.RI "t_dmaAddressReload \fBt_destAddReload\fP"
.br
.ti -1c
.RI "uint16_t \fBs_blockSize\fP"
.br
.ti -1c
.RI "t_dmaBurstMode \fBt_burstMode\fP"
.br
.ti -1c
.RI "t_dmaTransferType \fBt_transferType\fP"
.br
.ti -1c
.RI "t_dmaTriggerSource \fBt_triggerSrc\fP"
.br
.ti -1c
.RI "int8_t \fBc_repeatCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
