.TH "t_dmaCntrlConfig" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_dmaCntrlConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_bufferingMode \fBt_buffMode\fP"
.br
.ti -1c
.RI "t_channelPriority \fBt_chanPriority\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
