.TH "t_dmaChan" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_dmaChan \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_dmaChanId \fBt_id\fP"
.br
.ti -1c
.RI "bool \fBb_validConfig\fP"
.br
.ti -1c
.RI "uint8_t \fBc_intCount\fP"
.br
.ti -1c
.RI "DMA_CH_t * \fBpt_dma\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
