.TH "t_ellipsoidCal" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_ellipsoidCal \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_insCalStatus \fBt_status\fP"
.br
.ti -1c
.RI "int16_t * \fBps_R\fP"
.br
.ti -1c
.RI "int16_t * \fBps_bias\fP"
.br
.ti -1c
.RI "int16_t * \fBps_scale\fP"
.br
.ti -1c
.RI "int8_t \fBc_n\fP"
.br
.ti -1c
.RI "int16_t \fBs_env\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
