.TH "t_gpioConf" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_gpioConf \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBc_inputMask\fP"
.br
.ti -1c
.RI "uint8_t \fBc_outputMask\fP"
.br
.ti -1c
.RI "bool \fBb_setOutputLow\fP"
.br
.ti -1c
.RI "t_pullConf \fBt_inConf\fP"
.br
.ti -1c
.RI "t_pullConf \fBt_outConf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
