.TH "t_intChanMap" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_intChanMap \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart1Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart2Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart3Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart4Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart5Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart6Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart7Chan\fP"
.br
.ti -1c
.RI "\fBt_uartChanHndl\fP * \fBpt_uart8Chan\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
