.TH "t_insDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_insDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_SEMHANDLE \fBt_mutex\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_rxBlockingSem\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.ti -1c
.RI "t_UARTHNDL \fBt_uHandle\fP"
.br
.ti -1c
.RI "t_TWIHNDL \fBt_tHandle\fP"
.br
.ti -1c
.RI "int16_t \fBas_dcm\fP [3][3]"
.br
.ti -1c
.RI "\fBt_magDev\fP \fBt_mag\fP"
.br
.ti -1c
.RI "\fBt_gyroDev\fP \fBt_gyro\fP"
.br
.ti -1c
.RI "\fBt_accelDev\fP \fBt_accel\fP"
.br
.ti -1c
.RI "int16_t \fBas_dcmAttitude\fP [3]"
.br
.ti -1c
.RI "uint32_t \fBi_lastTime\fP"
.br
.ti -1c
.RI "float \fBgaf_scratchBuf\fP [(INS_MAX_CAL_SAMPLES *INS_EF_NUM_COEF *2)+(INS_EF_NUM_COEF *INS_EF_NUM_COEF)]"
.br
.ti -1c
.RI "int8_t \fBc_HWrtPtr\fP"
.br
.ti -1c
.RI "int16_t \fBas_P\fP [9][9]"
.br
.ti -1c
.RI "int32_t \fBai_resVar\fP [3]"
.br
.ti -1c
.RI "int8_t \fBc_inhibitKalmanCorr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
