.TH "t_lcdDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_lcdDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_SEMHANDLE \fBt_mutex\fP"
.br
.ti -1c
.RI "t_UARTHNDL \fBt_uHandle\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numRows\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numColumns\fP"
.br
.ti -1c
.RI "\fBt_cursPos\fP \fBt_cPos\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
