.TH "t_magDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_magDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBas_R\fP [3][3]"
.br
.ti -1c
.RI "int16_t \fBas_scale\fP [3]"
.br
.ti -1c
.RI "int16_t \fBas_bias\fP [3]"
.br
.ti -1c
.RI "int16_t \fBs_calMagFieldStr\fP"
.br
.ti -1c
.RI "t_insCalStatus \fBt_cal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
