.TH "t_mailbox" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_mailbox \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_SEMHANDLE \fBt_mutex\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_semFillCount\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_semEmptyCount\fP"
.br
.ti -1c
.RI "uint16_t \fBs_queueSize\fP"
.br
.ti -1c
.RI "uint16_t \fBs_queueDepth\fP"
.br
.ti -1c
.RI "uint16_t \fBs_wrPtr\fP"
.br
.ti -1c
.RI "uint16_t \fBs_rdPtr\fP"
.br
.ti -1c
.RI "int16_t \fBs_numMessages\fP"
.br
.ti -1c
.RI "t_semMode \fBt_writeMode\fP"
.br
.ti -1c
.RI "t_semMode \fBt_readMode\fP"
.br
.ti -1c
.RI "bool \fBb_wrtFromInt\fP"
.br
.ti -1c
.RI "bool \fBb_multRdWr\fP"
.br
.ti -1c
.RI "int8_t * \fBpc_queue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
