.TH "t_navStruct" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_navStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_navState \fBt_nxtState\fP"
.br
.ti -1c
.RI "t_navState \fBt_curState\fP"
.br
.ti -1c
.RI "t_DEVHANDLE \fBt_insHndl\fP"
.br
.ti -1c
.RI "t_DEVHANDLE \fBt_signalHndl\fP"
.br
.ti -1c
.RI "t_THRDHANDLE \fBt_navThread\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_mutex\fP"
.br
.ti -1c
.RI "int16_t \fBas_cal\fP [3]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
