.TH "t_platformTestObject" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_platformTestObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_THRDHANDLE \fBt_platformTest\fP"
.br
.ti -1c
.RI "t_UARTHNDL \fBt_uHandle\fP"
.br
.ti -1c
.RI "t_MAILBOXHNDL \fBt_inMbxHndl\fP"
.br
.ti -1c
.RI "t_MAILBOXHNDL \fBt_outMbxHndl\fP"
.br
.ti -1c
.RI "t_DMAHNDL \fBt_txDmaHandle\fP"
.br
.ti -1c
.RI "t_DMAHNDL \fBt_rxDmaHandle\fP"
.br
.ti -1c
.RI "t_TWIHNDL \fBt_twiSlave\fP"
.br
.ti -1c
.RI "t_TWIHNDL \fBt_twiMaster\fP"
.br
.ti -1c
.RI "t_TIMERHNDL \fBt_tHandle\fP"
.br
.ti -1c
.RI "t_GPIOHNDL \fBt_gHandle\fP"
.br
.ti -1c
.RI "t_SPIHNDL \fBt_spiMaster\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numBytesTrans\fP"
.br
.ti -1c
.RI "int8_t \fBac_txData\fP [MAX_BUFFER_SIZE]"
.br
.ti -1c
.RI "int8_t \fBac_rxData\fP [MAX_BUFFER_SIZE]"
.br
.ti -1c
.RI "t_THRDHANDLE \fBt_platformTest2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
