.TH "t_printObject" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_printObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_DEVHANDLE \fBt_printfHndl\fP"
.br
.ti -1c
.RI "t_DEVHANDLE \fBt_logFileHndl\fP"
.br
.ti -1c
.RI "t_BUFFHANDLE \fBt_logBuffer\fP"
.br
.ti -1c
.RI "uint8_t \fBc_termDbgLevel\fP"
.br
.ti -1c
.RI "bool \fBb_wrtLogFile\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
