.TH "t_sdSetup" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_sdSetup \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_spiChanId \fBt_spiChan\fP"
.br
.ti -1c
.RI "t_gpioPort \fBt_csPort\fP"
.br
.ti -1c
.RI "uint8_t \fBt_csPin\fP"
.br
.ti -1c
.RI "uint8_t \fBc_majorNum\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
