.TH "t_signalDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_signalDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_SEMHANDLE \fBt_mutex\fP"
.br
.ti -1c
.RI "uint8_t \fBc_signalPort\fP"
.br
.ti -1c
.RI "uint8_t \fBac_ledPins\fP [SIGNAL_MAX_LEDS]"
.br
.ti -1c
.RI "uint8_t \fBc_allLedMask\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
