.TH "t_sonarDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_sonarDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_semHandle \fBt_mutex\fP"
.br
.ti -1c
.RI "t_semHandle \fBt_blockingSem\fP"
.br
.ti -1c
.RI "t_GPIOHNDL \fBt_gpioHandle\fP"
.br
.ti -1c
.RI "t_ADCCHANHNDL \fBt_adcHandle\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.ti -1c
.RI "uint16_t \fBs_currMeas\fP"
.br
.ti -1c
.RI "uint32_t \fBi_measSum\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numAvr\fP"
.br
.ti -1c
.RI "bool \fBb_measEnabled\fP"
.br
.ti -1c
.RI "uint8_t \fBc_avrCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
