.TH "t_spiConfig" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_spiConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_spiMode \fBt_spiMd\fP"
.br
.ti -1c
.RI "t_spiOperation \fBt_spiOp\fP"
.br
.ti -1c
.RI "t_spiDataOrder \fBt_spiOrder\fP"
.br
.ti -1c
.RI "uint32_t \fBi_baudRate\fP"
.br
.ti -1c
.RI "bool \fBb_enDma\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
