.TH "t_spiChanHndl" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_spiChanHndl \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_spiChanId \fBt_id\fP"
.br
.ti -1c
.RI "int32_t \fBi_baudRate\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.ti -1c
.RI "t_spiOperation \fBt_spiOp\fP"
.br
.ti -1c
.RI "SPI_t * \fBpt_spi\fP"
.br
.ti -1c
.RI "bool \fBb_busLocked\fP"
.br
.ti -1c
.RI "void * \fBpt_activeUser\fP"
.br
.ti -1c
.RI "t_LINKHNDL \fBt_linkHndl\fP"
.br
.ti -1c
.RI "t_DMAHNDL \fBt_txDmaHndl\fP"
.br
.ti -1c
.RI "t_DMAHNDL \fBt_rxDmaHndl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
