.TH "t_spiUserHndl" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_spiUserHndl \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBpf_funPtr\fP )(int8_t *pc_data, uint16_t s_length)"
.br
.ti -1c
.RI "int8_t * \fBpc_txData\fP"
.br
.ti -1c
.RI "int8_t * \fBpc_rxData\fP"
.br
.ti -1c
.RI "uint16_t \fBs_bufLength\fP"
.br
.ti -1c
.RI "uint16_t \fBs_bufIndex\fP"
.br
.ti -1c
.RI "t_gpioPort \fBt_csPort\fP"
.br
.ti -1c
.RI "uint8_t \fBc_csPin\fP"
.br
.ti -1c
.RI "\fBt_spiChanHndl\fP * \fBpt_spiChanHndl\fP"
.br
.ti -1c
.RI "t_GPIOHNDL \fBt_csIntHndl\fP"
.br
.ti -1c
.RI "bool \fBb_enCs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
