.TH "t_stMnObject" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_stMnObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBc_nextState\fP"
.br
.ti -1c
.RI "uint8_t \fBc_currState\fP"
.br
.ti -1c
.RI "uint8_t \fBc_prevState\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numStates\fP"
.br
.ti -1c
.RI "int32_t \fBi_stateData\fP"
.br
.ti -1c
.RI "funPtr_t * \fBpv_funcMap\fP"
.br
.ti -1c
.RI "uint8_t * \fBpc_transMap\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
