.TH "t_sysTime" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_sysTime \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBl_msec\fP"
.br
.ti -1c
.RI "uint64_t \fBl_ticks\fP"
.br
.ti -1c
.RI "uint16_t \fBs_days\fP"
.br
.ti -1c
.RI "uint8_t \fBc_hours\fP"
.br
.ti -1c
.RI "uint8_t \fBc_min\fP"
.br
.ti -1c
.RI "uint8_t \fBc_sec\fP"
.br
.ti -1c
.RI "uint32_t \fBi_usec\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
