.TH "t_timerConfig" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_timerConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_wfMode \fBt_mode\fP"
.br
.ti -1c
.RI "t_countDir \fBt_dir\fP"
.br
.ti -1c
.RI "float \fBf_period\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
