.TH "t_twiConfig" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_twiConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_twiMode \fBt_mode\fP"
.br
.ti -1c
.RI "uint32_t \fBi_baud\fP"
.br
.ti -1c
.RI "uint8_t \fBc_slaveAddress\fP"
.br
.ti -1c
.RI "int8_t(* \fBpf_transComplete\fP )(t_twiStatus t_status, int8_t c_data)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
