.TH "t_uartChanHndl" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_uartChanHndl \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_uartChanId \fBt_id\fP"
.br
.ti -1c
.RI "int32_t \fBi_baudRate\fP"
.br
.ti -1c
.RI "float \fBf_percentBaudError\fP"
.br
.ti -1c
.RI "USART_t * \fBpt_uart\fP"
.br
.ti -1c
.RI "bool \fBb_txBusLocked\fP"
.br
.ti -1c
.RI "bool \fBb_rxBusLocked\fP"
.br
.ti -1c
.RI "int8_t * \fBpc_txData\fP"
.br
.ti -1c
.RI "int8_t * \fBpc_rxData\fP"
.br
.ti -1c
.RI "uint16_t \fBs_txBufLength\fP"
.br
.ti -1c
.RI "uint16_t \fBs_rxBufLength\fP"
.br
.ti -1c
.RI "uint16_t \fBs_txBufIndex\fP"
.br
.ti -1c
.RI "uint16_t \fBs_rxBufIndex\fP"
.br
.ti -1c
.RI "t_DMAHNDL \fBt_txDmaHndl\fP"
.br
.ti -1c
.RI "t_DMAHNDL \fBt_rxDmaHndl\fP"
.br
.ti -1c
.RI "void(* \fBpf_rxCallBack\fP )(uint16_t s_data)"
.br
.ti -1c
.RI "void(* \fBpf_txCallBack\fP )(uint16_t s_size)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
