.TH "t_uartConfig" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_uartConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_comMode \fBt_comMd\fP"
.br
.ti -1c
.RI "t_charSize \fBt_charSz\fP"
.br
.ti -1c
.RI "t_parityMode \fBt_parityMd\fP"
.br
.ti -1c
.RI "t_stopBitMode \fBt_stopBitMd\fP"
.br
.ti -1c
.RI "uint32_t \fBi_baudRate\fP"
.br
.ti -1c
.RI "bool \fBb_enTxDma\fP"
.br
.ti -1c
.RI "bool \fBb_enRxDma\fP"
.br
.ti -1c
.RI "void(* \fBpf_rxCallBack\fP )(uint16_t s_data)"
.br
.ti -1c
.RI "void(* \fBpf_txCallBack\fP )(uint16_t s_size)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
