.TH "t_wiflyDev" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_wiflyDev \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_SEMHANDLE \fBt_rxMutex\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_txMutex\fP"
.br
.ti -1c
.RI "t_SEMHANDLE \fBt_rxBlockingSem\fP"
.br
.ti -1c
.RI "uint8_t * \fBpc_rxBuffer\fP"
.br
.ti -1c
.RI "uint8_t * \fBpc_txBuffer\fP"
.br
.ti -1c
.RI "t_UARTHNDL \fBt_uHandle\fP"
.br
.ti -1c
.RI "uint8_t \fBc_resetPort\fP"
.br
.ti -1c
.RI "uint8_t \fBc_resetPin\fP"
.br
.ti -1c
.RI "uint8_t \fBc_numUsers\fP"
.br
.ti -1c
.RI "char \fBac_respString\fP [WIFLY_RESP_STRING_MAX]"
.br
.ti -1c
.RI "bool \fBb_respFound\fP"
.br
.ti -1c
.RI "uint8_t \fBc_respIndex\fP"
.br
.ti -1c
.RI "uint8_t \fBc_respSize\fP"
.br
.ti -1c
.RI "bool \fBb_enCmdMode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
