.TH "twiChanHndl" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
twiChanHndl \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_twiChanId \fBt_id\fP"
.br
.ti -1c
.RI "bool \fBb_validConfig\fP"
.br
.ti -1c
.RI "int32_t \fBi_baudRate\fP"
.br
.ti -1c
.RI "t_twiStatus \fBt_status\fP"
.br
.ti -1c
.RI "TWI_MASTER_t * \fBpt_master\fP"
.br
.ti -1c
.RI "TWI_SLAVE_t * \fBpt_slave\fP"
.br
.ti -1c
.RI "int8_t(* \fBpf_transComplete\fP )(t_twiStatus t_status, int8_t c_data)"
.br
.ti -1c
.RI "uint8_t * \fBpc_data\fP"
.br
.ti -1c
.RI "uint16_t \fBs_length\fP"
.br
.ti -1c
.RI "uint16_t \fBs_bufIndex\fP"
.br
.ti -1c
.RI "\fBt_sysTime\fP \fBt_lastIntTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
