.TH "UDP" 3 "Sun Mar 2 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UDP \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual uint8_t \fBbegin\fP (uint16_t)=0"
.br
.ti -1c
.RI "virtual void \fBstop\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBbeginPacket\fP (\fBIPAddress\fP ip, uint16_t port)=0"
.br
.ti -1c
.RI "virtual int \fBbeginPacket\fP (const char *host, uint16_t port)=0"
.br
.ti -1c
.RI "virtual int \fBendPacket\fP ()=0"
.br
.ti -1c
.RI "virtual size_t \fBwrite\fP (uint8_t)=0"
.br
.ti -1c
.RI "virtual size_t \fBwrite\fP (const uint8_t *buffer, size_t size)=0"
.br
.ti -1c
.RI "virtual int \fBparsePacket\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBavailable\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBread\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBread\fP (unsigned char *buffer, size_t len)=0"
.br
.ti -1c
.RI "virtual int \fBread\fP (char *buffer, size_t len)=0"
.br
.ti -1c
.RI "virtual int \fBpeek\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBflush\fP ()=0"
.br
.ti -1c
.RI "virtual \fBIPAddress\fP \fBremoteIP\fP ()=0"
.br
.ti -1c
.RI "virtual uint16_t \fBremotePort\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "uint8_t * \fBrawIPAddress\fP (\fBIPAddress\fP &addr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
